### ISSUE TITLE
Please add "Disable DHE will be enabled after you restart"

### ISSUE THREAD

**Issue by davidhedlund** [martinthomson/disable-dhe#1]
For a reliable test you can use https://dhe512.zmap.io/ . If the page doesn't load, then you are not vulnerable to the logjam attack.

I found out that the browser needed to be restarted to take effect by using the above link. Can you please add a "Disable DHE will be enabled after you restart" that pop-up when the add-on have been installed and/or enabled/disabled?

**Comment by martinthomson** [comment]
The addon disables DHE immediately after installation.  The browser does not need a restart.

**Comment by davidhedlund** [comment]
I can confirm that the current version of Disable DHE is restartless.
