### ISSUE TITLE
Which Firefox ESR version are safe?

### ISSUE THREAD

**Issue by davidhedlund** [martinthomson/disable-dhe#2]
"Firefox 39 will include changes that will increase the minimum strength of keys to 1024 bits." - https://addons.mozilla.org/en-US/firefox/addon/disable-dhe/

The page didn't mention which Firefox ESR version that are safe from logjam attacks. Which one is it?

**Comment by martinthomson** [comment]
The next ESR 38 will contain the fix.

**Comment by davidhedlund** [comment]
@martinthomson 38.0.2?

**Comment by martinthomson** [comment]
Yes, I believe that 38.0.2 releases on June 29.

**Comment by davidhedlund** [comment]
@martinthomson Thanks.

Also, "Firefox 39 will include changes that will increase the minimum strength of keys to 1024 bits." - https://addons.mozilla.org/en-US/firefox/addon/disable-dhe/ Which Firefox 39.x.x will contain this fix?

**Comment by martinthomson** [comment]
All versions of 39 (unless you are downloading old versions of Developer Edition or early Beta version) have the fix.

**Comment by davidhedlund** [comment]
@martinthomson So starting 39.0, right? Just to make this formal.

**Comment by martinthomson** [comment]
Correct

**Comment by davidhedlund** [comment]
@martinthomson Excellent. Thanks for your support. I recommended the GNU IceCat maintainer to base next version of IceCat on Firefox ESR 38.0.2 instead of 38.0.

**Comment by davidhedlund** [comment]
@martinthomson Can you please update https://addons.mozilla.org/en-US/firefox/addon/disable-dhe/ with: "**Firefox 39.0 and Firefox ESR 38.0.2** will include changes that will increase the minimum strength of keys to 1024 bits."?

**Comment by martinthomson** [comment]
Done.

**Comment by davidhedlund** [comment]
@martinthomson Thank you once again.
